### ISSUE TITLE
APP 闪退，无法启动

### ISSUE THREAD

**Issue by onichan0923** [FlowerBlackG/FakeRun#7]
1.2 及 1.3 版本稳定复现，请求修复，麻烦了
![Screenshot_20240920-183557](https://github.com/user-attachments/assets/2f6ca100-ae1f-4f09-a294-a3b32264ba87)

**Comment by gfjdh** [comment]
估计是获取系统时间出了问题，临时解决方案：把系统时间调到2023年

**Comment by FlowerBlackG** [comment]
你好，该问题是由更新服务器安全证书过期导致。现已修复。谢谢反馈！
